#!/usr/bin/env python3

import json
import sys
from pathlib import Path


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("Usage: {} ROOTDIR\n".format(sys.argv[0]))
        sys.exit(1)
    json.dump(list(map(lambda path: {
        'name': '{}({}) {} {}/{}'.format(*path.parts),
        'file': str(path)
    }, Path(sys.argv[1]).glob('*/*/*/*/*.json'))), sys.stdout)


if __name__ == "__main__":
    main()
